var stimuliData = [
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_01",
    "Clip ID": "M1_01",
    "Duration (s)": "2.181",
    "# of IPs": "1",
    "# of words": "11",
    "Speech rate (words per s)": "5.043558001",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "Uh I was on the verge of starting my first relationship"
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_02",
    "Clip ID": "M1_02",
    "Duration (s)": "1.542",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "4.539559014",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "So you you don't have to like"
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_04",
    "Clip ID": "M1_03",
    "Duration (s)": "2.162",
    "# of IPs": "1",
    "# of words": "11",
    "Speech rate (words per s)": "5.087881591",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "It was not terrible because at that point of my life"
  },
  {
    "Speaker ID": "M1",
    "Name": "JOHN",
    "Gender": "male",
    "VER 3 Name": "JOHN_06",
    "Clip ID": "M1_04",
    "Duration (s)": "2.266",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "3.530450132",
    "Link": "https://youtu.be/-jbJeIZ0mJY?t=108",
    "Transcription": "She travelled to Hong Kong with her family"
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_04",
    "Clip ID": "M2_01",
    "Duration (s)": "2.032",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "3.937007874",
    "Link": "https://youtu.be/zRZu05R_eD8?t=402",
    "Transcription": "I think the dinner how much was it"
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_05",
    "Clip ID": "M2_02",
    "Duration (s)": "2.306",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.03555941",
    "Link": "https://youtu.be/zRZu05R_eD8?t=550",
    "Transcription": "When did you first start doing content"
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_06",
    "Clip ID": "M2_03",
    "Duration (s)": "2.423",
    "# of IPs": "1",
    "# of words": "11",
    "Speech rate (words per s)": "4.539826661",
    "Link": "https://youtu.be/P5kKKe_-qJ8?t=1138",
    "Transcription": "After this the moment the podcast end we are heading there"
  },
  {
    "Speaker ID": "M2",
    "Name": "LUKE",
    "Gender": "male",
    "VER 3 Name": "LUKE_07",
    "Clip ID": "M2_04",
    "Duration (s)": "2.417",
    "# of IPs": "1",
    "# of words": "14",
    "Speech rate (words per s)": "5.79230451",
    "Link": "https://youtu.be/P5kKKe_-qJ8?t=1826",
    "Transcription": "Then I told them you know what never mind I'm not interested any more"
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_02",
    "Clip ID": "M3_01",
    "Duration (s)": "2.489",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "2.410606669",
    "Link": "",
    "Transcription": "I self-identify as a historian"
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_03",
    "Clip ID": "M3_02",
    "Duration (s)": "2.384",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "3.775167785",
    "Link": "",
    "Transcription": "That's what I am first and foremost a historian"
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_04",
    "Clip ID": "M3_03",
    "Duration (s)": "2.233",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.134796238",
    "Link": "",
    "Transcription": "But I've left that life behind me"
  },
  {
    "Speaker ID": "M3",
    "Name": "PJ",
    "Gender": "male",
    "VER 3 Name": "PJ_08",
    "Clip ID": "M3_04",
    "Duration (s)": "1.79",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "3.351955307",
    "Link": "",
    "Transcription": "I hurt my knee quite badly"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_07",
    "Clip ID": "M4_01",
    "Duration (s)": "1.953",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "4.096262161",
    "Link": "",
    "Transcription": "Did you manage to fulfil them right now"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_08",
    "Clip ID": "M4_02",
    "Duration (s)": "1.949",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "4.104669061",
    "Link": "",
    "Transcription": "I took the ATM card and I didn't"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_09",
    "Clip ID": "M4_03",
    "Duration (s)": "1.516",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.298153034",
    "Link": "",
    "Transcription": "Be a son to him"
  },
  {
    "Speaker ID": "M4",
    "Name": "SIMON",
    "Gender": "male",
    "VER 3 Name": "SIMON_10",
    "Clip ID": "M4_04",
    "Duration (s)": "1.754",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.990877993",
    "Link": "",
    "Transcription": "I message him in IG with my"
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_02",
    "Clip ID": "M5_01",
    "Duration (s)": "2",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.53713997",
    "Link": "https://youtu.be/1CFCXDiJH5g?t=287",
    "Transcription": "It's better to be factual about it"
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_06",
    "Clip ID": "M5_02",
    "Duration (s)": "2.08",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "3.846153846",
    "Link": "",
    "Transcription": "You walk out of the situation rather than"
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_07",
    "Clip ID": "M5_03",
    "Duration (s)": "2",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "4.603580563",
    "Link": "",
    "Transcription": "They say that it's not a good thing to"
  },
  {
    "Speaker ID": "M5",
    "Name": "TERENCE",
    "Gender": "male",
    "VER 3 Name": "TERENCE_08",
    "Clip ID": "M5_04",
    "Duration (s)": "2.091",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.347680536",
    "Link": "",
    "Transcription": "Just talking about how why some people"
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_01",
    "Clip ID": "F1_01",
    "Duration (s)": "2.319",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "4.312203536",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2308",
    "Transcription": "That person was asking me a question and I replied"
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_02",
    "Clip ID": "F1_02",
    "Duration (s)": "1.584",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "4.419191919",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2371",
    "Transcription": "I didn't mean it that way and"
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_06",
    "Clip ID": "F1_03",
    "Duration (s)": "2.334",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "2.999143102",
    "Link": "https://youtu.be/BsLVsJNv4wc?t=2308",
    "Transcription": "Certificate of sorts right a Youtube plaque"
  },
  {
    "Speaker ID": "F1",
    "Name": "ESTEE",
    "Gender": "female",
    "VER 3 Name": "ESTEE_07",
    "Clip ID": "F1_04",
    "Duration (s)": "2.44",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "3.68852459",
    "Link": "",
    "Transcription": "Believe that you cannot feel anything while you're doing"
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_03",
    "Clip ID": "F2_01",
    "Duration (s)": "1.859",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "4.303388919",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1326",
    "Transcription": "I guess with every small step it helps"
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_07",
    "Clip ID": "F2_02",
    "Duration (s)": "2.157",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "4.172461752",
    "Link": "",
    "Transcription": "Buy each other roses and give each other cards"
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_09",
    "Clip ID": "F2_03",
    "Duration (s)": "2.442",
    "# of IPs": "1",
    "# of words": "13",
    "Speech rate (words per s)": "5.323505324",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "If let's say like you plug in your stuff into the switch right"
  },
  {
    "Speaker ID": "F2",
    "Name": "GERMAINE",
    "Gender": "female",
    "VER 3 Name": "GERMAINE_11",
    "Clip ID": "F2_04",
    "Duration (s)": "1.686",
    "# of IPs": "1",
    "# of words": "4",
    "Speech rate (words per s)": "2.372479241",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "Probably some household goods"
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_09",
    "Clip ID": "F3_01",
    "Duration (s)": "1.898",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "3.688092729",
    "Link": "https://youtu.be/ZqG4tyevNwU?t=1437",
    "Transcription": "Regular products may cost like eleven dollars"
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_11",
    "Clip ID": "F3_02",
    "Duration (s)": "2.276",
    "# of IPs": "1",
    "# of words": "11",
    "Speech rate (words per s)": "4.833040422",
    "Link": "",
    "Transcription": "I mean honestly I'll say first it's so hard for us"
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_12",
    "Clip ID": "F3_03",
    "Duration (s)": "1.896",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "4.746835443",
    "Link": "",
    "Transcription": "A lot of people put their stuff up there"
  },
  {
    "Speaker ID": "F3",
    "Name": "HAZELLE",
    "Gender": "female",
    "VER 3 Name": "HAZELLE_13",
    "Clip ID": "F3_04",
    "Duration (s)": "1.663",
    "# of IPs": "1",
    "# of words": "8",
    "Speech rate (words per s)": "4.810583283",
    "Link": "",
    "Transcription": "It can go up to like four times"
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_03",
    "Clip ID": "F4_01",
    "Duration (s)": "1.921",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "4.685059865",
    "Link": "",
    "Transcription": "Are on the same level I think that's ok"
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_04",
    "Clip ID": "F4_02",
    "Duration (s)": "2.483",
    "# of IPs": "1",
    "# of words": "10",
    "Speech rate (words per s)": "4.027386226",
    "Link": "",
    "Transcription": "Really really like trying to show support to the person"
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_05",
    "Clip ID": "F4_03",
    "Duration (s)": "2.523",
    "# of IPs": "1",
    "# of words": "14",
    "Speech rate (words per s)": "5.548949663",
    "Link": "",
    "Transcription": "I don't think they catch feelings but they just become more attached to them"
  },
  {
    "Speaker ID": "F4",
    "Name": "JOSEPHINE",
    "Gender": "female",
    "VER 3 Name": "LEEN_06",
    "Clip ID": "F4_04",
    "Duration (s)": "1.514",
    "# of IPs": "1",
    "# of words": "7",
    "Speech rate (words per s)": "4.623513871",
    "Link": "",
    "Transcription": "Slowly put the fish in the water"
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_06",
    "Clip ID": "F5_01",
    "Duration (s)": "2.022",
    "# of IPs": "1",
    "# of words": "9",
    "Speech rate (words per s)": "4.451038576",
    "Link": "https://youtu.be/aFLgw8VpkPw?t=849",
    "Transcription": "But people have been telling me things about Junior"
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_07",
    "Clip ID": "F5_02",
    "Duration (s)": "1.467",
    "# of IPs": "1",
    "# of words": "6",
    "Speech rate (words per s)": "4.08997955",
    "Link": "https://youtu.be/aFLgw8VpkPw?t=849",
    "Transcription": "I don't want to believe this"
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_08",
    "Clip ID": "F5_03",
    "Duration (s)": "1.587",
    "# of IPs": "1",
    "# of words": "5",
    "Speech rate (words per s)": "3.150598614",
    "Link": "",
    "Transcription": "It was just through message"
  },
  {
    "Speaker ID": "F5",
    "Name": "NINA",
    "Gender": "female",
    "VER 3 Name": "NINA_09",
    "Clip ID": "F5_04",
    "Duration (s)": "1.979",
    "# of IPs": "1",
    "# of words": "11",
    "Speech rate (words per s)": "5.558362809",
    "Link": "",
    "Transcription": "As long as you tell me that we are still together"
  }
];